const currency= [
    { text: 'Poland', id: 'PLN' },
    { text: 'European Union', id: 'EUR' },
    { text: 'USA', id: 'USD' },
    { text: 'UK', id: 'GBP' },
    { text: 'Switzerland', id: 'CHF' },
    { text: 'Austria', id: 'AUD' },
    { text: 'Bulgaria', id: 'BGN' },
    { text: 'Brazil', id: 'BRL' },
    { text: 'Canada', id: 'CAD' },
    { text: 'Chile', id: 'CLP' },
    { text: 'China', id: 'CNY' },
    { text: 'Czech Republic', id: 'CZK' },
    { text: 'Denmark', id: 'DKK' },
    { text: 'Hong Kong', id: 'HKD' },
    { text: 'Croatia', id: 'HRK' },
    { text: 'Hungary', id: 'HUF' },
    { text: 'Indonesia', id: 'IDR' },
    { text: 'Israel', id: 'ILS' },
    { text: 'India', id: 'INR' },
    { text: 'Iceland', id: 'ISK' },
    { text: 'Japan', id: 'JPY' },
    { text: 'South Korea', id: 'KRW' },
    { text: 'Mexico', id: 'MXN' },
    { text: 'Malaysia', id: 'MYR' },
    { text: 'Norway', id: 'NOK' },
    { text: 'New Zealand', id: 'NZD' },
    { text: 'Philippines', id: 'PHP' },
    { text: 'Romania', id: 'RON' },
    { text: 'Sweden', id: 'SEK' },
    { text: 'Singapore', id: 'SGD' },
    { text: 'Thailand', id: 'THB' },
    { text: 'Turkey', id: 'TRY' },
    { text: 'Ukraine', id: 'UAH' },
    { text: 'IMF (SDR)', id: 'XDR' },
    { text: 'South Republic Africa', id: 'ZAR' }
]

export default currency;
